export const ABI = {
  address: "0x7fe2b067b33642d6e5fea417452abeb131bb80ea07ad5d2ff0a0f58292238393",
  name: "launchpad",
  friends: [],
  exposed_functions: [
    {
      name: "accept_admin",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer"],
      return: [],
    },
    {
      name: "batch_mint_nft",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        "&signer",
        "0x1::object::Object<0x4::collection::Collection>",
        "u64",
      ],
      return: [],
    },
    {
      name: "create_collection",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: [
        "&signer",
        "0x1::string::String",
        "0x1::string::String",
        "0x1::string::String",
        "u64",
        "0x1::option::Option<u64>",
        "0x1::option::Option<u64>",
        "0x1::option::Option<vector<address>>",
        "0x1::option::Option<u64>",
        "0x1::option::Option<u64>",
        "0x1::option::Option<u64>",
        "0x1::option::Option<u64>",
        "0x1::option::Option<u64>",
        "0x1::option::Option<u64>",
        "0x1::option::Option<u64>",
        "0x1::option::Option<u64>",
      ],
      return: [],
    },
    {
      name: "get_active_or_next_mint_stage",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: ["0x1::object::Object<0x4::collection::Collection>"],
      return: ["0x1::option::Option<0x1::string::String>"],
    },
    {
      name: "get_admin",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ["address"],
    },
    {
      name: "get_mint_fee_collector",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ["address"],
    },
    {
      name: "get_mint_fee_per_nft",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [
        "0x1::object::Object<0x4::collection::Collection>",
        "0x1::string::String",
      ],
      return: ["u64"],
    },
    {
      name: "get_mint_stage_start_and_end_time",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [
        "0x1::object::Object<0x4::collection::Collection>",
        "0x1::string::String",
      ],
      return: ["u64", "u64"],
    },
    {
      name: "get_registry",
      visibility: "public",
      is_entry: false,
      is_view: true,
      generic_type_params: [],
      params: [],
      return: ["vector<0x1::object::Object<0x4::collection::Collection>>"],
    },
    {
      name: "mint_nft",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "0x1::object::Object<0x4::collection::Collection>"],
      return: [],
    },
    {
      name: "set_pending_admin",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "address"],
      return: [],
    },
    {
      name: "update_mint_fee_collector",
      visibility: "public",
      is_entry: true,
      is_view: false,
      generic_type_params: [],
      params: ["&signer", "address"],
      return: [],
    },
  ],
  structs: [
    {
      name: "BatchMintNftsEvent",
      is_native: false,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "collection_obj",
          type: "0x1::object::Object<0x4::collection::Collection>",
        },
        {
          name: "nft_objs",
          type: "vector<0x1::object::Object<0x4::token::Token>>",
        },
        { name: "recipient_addr", type: "address" },
        { name: "total_mint_fee", type: "u64" },
      ],
    },
    {
      name: "BatchPreMintNftsEvent",
      is_native: false,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "collection_obj",
          type: "0x1::object::Object<0x4::collection::Collection>",
        },
        {
          name: "nft_objs",
          type: "vector<0x1::object::Object<0x4::token::Token>>",
        },
        { name: "recipient_addr", type: "address" },
      ],
    },
    {
      name: "CollectionConfig",
      is_native: false,
      abilities: ["key"],
      generic_type_params: [],
      fields: [
        {
          name: "mint_fee_per_nft_by_stages",
          type: "0x1::simple_map::SimpleMap<0x1::string::String, u64>",
        },
        {
          name: "collection_owner_obj",
          type: "0x1::object::Object<0x7fe2b067b33642d6e5fea417452abeb131bb80ea07ad5d2ff0a0f58292238393::launchpad::CollectionOwnerObjConfig>",
        },
      ],
    },
    {
      name: "CollectionOwnerObjConfig",
      is_native: false,
      abilities: ["key"],
      generic_type_params: [],
      fields: [
        {
          name: "collection_obj",
          type: "0x1::object::Object<0x4::collection::Collection>",
        },
        { name: "extend_ref", type: "0x1::object::ExtendRef" },
      ],
    },
    {
      name: "Config",
      is_native: false,
      abilities: ["key"],
      generic_type_params: [],
      fields: [
        { name: "admin_addr", type: "address" },
        { name: "pending_admin_addr", type: "0x1::option::Option<address>" },
        { name: "mint_fee_collector_addr", type: "address" },
      ],
    },
    {
      name: "CreateCollectionEvent",
      is_native: false,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        { name: "creator_addr", type: "address" },
        {
          name: "collection_owner_obj",
          type: "0x1::object::Object<0x7fe2b067b33642d6e5fea417452abeb131bb80ea07ad5d2ff0a0f58292238393::launchpad::CollectionOwnerObjConfig>",
        },
        {
          name: "collection_obj",
          type: "0x1::object::Object<0x4::collection::Collection>",
        },
        { name: "max_supply", type: "u64" },
        { name: "name", type: "0x1::string::String" },
        { name: "description", type: "0x1::string::String" },
        { name: "uri", type: "0x1::string::String" },
        { name: "pre_mint_amount", type: "0x1::option::Option<u64>" },
        { name: "allowlist", type: "0x1::option::Option<vector<address>>" },
        { name: "allowlist_start_time", type: "0x1::option::Option<u64>" },
        { name: "allowlist_end_time", type: "0x1::option::Option<u64>" },
        {
          name: "allowlist_mint_limit_per_addr",
          type: "0x1::option::Option<u64>",
        },
        {
          name: "allowlist_mint_fee_per_nft",
          type: "0x1::option::Option<u64>",
        },
        { name: "public_mint_start_time", type: "0x1::option::Option<u64>" },
        { name: "public_mint_end_time", type: "0x1::option::Option<u64>" },
        {
          name: "public_mint_limit_per_addr",
          type: "0x1::option::Option<u64>",
        },
        { name: "public_mint_fee_per_nft", type: "0x1::option::Option<u64>" },
      ],
    },
    {
      name: "MintNftEvent",
      is_native: false,
      abilities: ["drop", "store"],
      generic_type_params: [],
      fields: [
        {
          name: "collection_obj",
          type: "0x1::object::Object<0x4::collection::Collection>",
        },
        { name: "nft_obj", type: "0x1::object::Object<0x4::token::Token>" },
        { name: "recipient_addr", type: "address" },
        { name: "mint_fee", type: "u64" },
      ],
    },
    {
      name: "Registry",
      is_native: false,
      abilities: ["key"],
      generic_type_params: [],
      fields: [
        {
          name: "collection_objects",
          type: "vector<0x1::object::Object<0x4::collection::Collection>>",
        },
      ],
    },
  ],
} as const;
