[package]
name = "digital_asset_launchpad"
version = "1.0.0"
authors = []

[addresses]
launchpad_addr = "_"
initial_creator_addr = "_"
minter = "_"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-framework.git", rev = "mainnet", subdir = "aptos-framework" }
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-framework.git", rev = "mainnet", subdir = "aptos-token-objects" }
TokenMinter = { git = "https://github.com/aptos-labs/token-minter.git", rev = "main", subdir = "token-minter" }

[dev-dependencies]
