import { Toaster } from '@/components/ui/sonner'
import { WalletProvider } from '@/components/WalletProvider.tsx'
import QueryProvider from '@/lib/providers'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
}

export default function RootLayout({
	children
}: {
	children: React.ReactNode
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<WalletProvider>
					<QueryProvider>
						<main id="root">{children}</main>
						<Toaster richColors position="top-right" />
					</QueryProvider>
				</WalletProvider>
			</body>
		</html>
	)
}
