name: Release

on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: read
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: https://registry.npmjs.org

      - name: Install Dependencies
        run: npm install

      - name: Build Packages
        run: npm run build

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Deprecate older versions
        run: |
          VERSION="$(node -p "require('./package.json').version")"
          npm deprecate "create-aptos-dapp@<${VERSION}" "This version is no longer supported. Please use create-aptos-dapp@latest."
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
